export interface BookingHistoryItem {
  id: string;
  bookingId: string;
  service: string;
  name: string;
  startDate: string;
  endDate: string;
  totalPrice: number;
  depositStatus: "Paid" | "Pending";
  remainingStatus: "Paid" | "Pending" | "Overdue";
  status: "Upcoming" | "Canceled" | "On Trip" | "Completed";
  agent: string;
}

export const mockBookingHistory: BookingHistoryItem[] = [
  {
    id: "bh-1",
    bookingId: "BK-2026-001",
    service: "Transportation",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Paid",
    status: "Upcoming",
    agent: "Sara M.",
  },
  {
    id: "bh-2",
    bookingId: "BK-2026-002",
    service: "Trips",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Pending",
    status: "Upcoming",
    agent: "Sara M.",
  },
  {
    id: "bh-3",
    bookingId: "BK-2026-003",
    service: "Trips",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Overdue",
    status: "Upcoming",
    agent: "Sara M.",
  },
  {
    id: "bh-4",
    bookingId: "BK-2026-004",
    service: "Hotels",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Paid",
    status: "Canceled",
    agent: "Sara M...",
  },
  {
    id: "bh-5",
    bookingId: "BK-2026-005",
    service: "Hotels",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Pending",
    status: "Canceled",
    agent: "Sara M.",
  },
  {
    id: "bh-6",
    bookingId: "BK-2026-006",
    service: "Transportation",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Overdue",
    status: "Canceled",
    agent: "Sara M.",
  },
  {
    id: "bh-7",
    bookingId: "BK-2026-007",
    service: "Trips",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Paid",
    status: "On Trip",
    agent: "Sara M.",
  },
  {
    id: "bh-8",
    bookingId: "BK-2026-008",
    service: "Hotels",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Paid",
    status: "Completed",
    agent: "Sara M.",
  },
  {
    id: "bh-9",
    bookingId: "BK-2026-009",
    service: "Hotels",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Paid",
    status: "Completed",
    agent: "Sara M.",
  },
  {
    id: "bh-10",
    bookingId: "BK-2026-010",
    service: "Transportation",
    name: "Santorini Island Explorer",
    startDate: "2024-07-15",
    endDate: "2024-07-22",
    totalPrice: 78900,
    depositStatus: "Paid",
    remainingStatus: "Paid",
    status: "Completed",
    agent: "Sara M.",
  },
];
