import { SummaryCardProps } from "@/components/dashboard/SummaryCard";
import { HotelBookingData } from "./types";

export const hotelSummaryMetrics: SummaryCardProps[] = [
  {
    label: "Total Hotel Bookings",
    value: "1,284",
    change: "-5.1%",
    trend: "down",
    tone: "pink",
    iconSrc: "/images/dashboard/booking/trips/total.svg", 
  },
  {
    label: "Upcoming Bookings",
    value: "20",
    change: "+8.2%",
    trend: "up",
    tone: "blue",
    iconSrc: "/images/dashboard/booking/hotels/upcoming_bookins.svg", 
  },
  {
    label: "Pending Deposits",
    value: "200",
    change: "-5.1%",
    trend: "down",
    tone: "orange",
    iconSrc: "/images/dashboard/booking/trips/pending.svg",
  },
  {
    label: "Completed Bookings",
    value: "5",
    change: "+8.2%",
    trend: "up",
    tone: "green",
    iconSrc: "/images/dashboard/booking/trips/completed.svg",
  },
];

export const MOCK_HOTEL_BOOKINGS: HotelBookingData[] = [
  {
    id: "HB-2026-100",
    customerName: "Ahmed Hassan",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Upcoming",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-101",
    customerName: "Linda Blair",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Pending",
    status: "Upcoming",
    source: "Agent",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-102",
    customerName: "Mohammad Karim",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Overdue",
    status: "Upcoming",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-103",
    customerName: "Ilham Budi Agung",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Canceled",
    source: "Agent",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-104",
    customerName: "John Bushmill",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Pending",
    status: "Canceled",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-105",
    customerName: "Linda Blair",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Overdue",
    status: "Refunded",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-106",
    customerName: "Josh Adam",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "On Trip",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-107",
    customerName: "Linda Blair",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-108",
    customerName: "Josh Adam",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-109",
    customerName: "Linda Blair",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-110",
    customerName: "Josh Adam",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-111",
    customerName: "Linda Blair",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
  {
    id: "HB-2026-112",
    customerName: "Josh Adam",
    checkIn: "May 25, 2026",
    checkOut: "May 25, 2026",
    roomsCount: 2,
    dateTime: "Mar 20, 10:00",
    paymentStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
    assignedAgentImage: "/images/dashboard/sidebar/user1.png",
  },
];
