import type { TripSummaryMetric, TripBookingRow } from "./types";

export const tripSummaryMetrics: TripSummaryMetric[] = [
  {
    label: "Total Trip Bookings",
    value: "1,284",
    change: "-5.1%",
    trend: "down",
    tone: "pink",
    icon: "booking/trips/total",
  },
  {
    label: "Upcoming Trips",
    value: "20",
    change: "+8.2%",
    trend: "up",
    tone: "blue",
    icon: "booking/trips/upcoming",
  },
  {
    label: "Pending Deposits",
    value: "200",
    change: "-5.1%",
    trend: "down",
    tone: "orange",
    icon: "booking/trips/pending",
  },
  {
    label: "Completed Trips",
    value: "5",
    change: "+8.2%",
    trend: "up",
    tone: "green",
    icon: "booking/trips/completed",
  },
];

const baseBookings: Omit<TripBookingRow, "id">[] = [
  {
    customerName: "Ahmed Hassan",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Private",
    depositStatus: "Paid",
    status: "Upcoming",
    source: "Website",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "Linda Blair",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Group",
    depositStatus: "Pending",
    status: "Upcoming",
    source: "Agent",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "Mohammad Karim",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Private",
    depositStatus: "Overdue",
    status: "Upcoming",
    source: "Website",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "John Bushmill",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Group",
    depositStatus: "Paid",
    status: "Canceled",
    source: "Agent",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "Linda Blair",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Private",
    depositStatus: "Pending",
    status: "Canceled",
    source: "Website",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "Linda Blair",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Group",
    depositStatus: "Overdue",
    status: "Refunded",
    source: "Website",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "Linda Blair",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Group",
    depositStatus: "Paid",
    status: "On Trip",
    source: "Website",
    assignedAgent: "Sara M.",
  },
  {
    customerName: "Linda Blair",
    tripName: "Santorini Island Explorer",
    dates: "2024-07-15 → 2024-07-22",
    tourType: "Group",
    depositStatus: "Paid",
    status: "Completed",
    source: "Website",
    assignedAgent: "Sara M.",
  }
];

export const mockTripsData: TripBookingRow[] = Array.from({ length: 15 }, (_, index) => ({
  ...baseBookings[index % baseBookings.length],
  id: `BK-2026-${String(index + 1).padStart(3, "0")}`,
}));
