import { CustomerRow, CustomerSummaryMetric } from "./types";

export const mockCustomerSummary: CustomerSummaryMetric[] = [
  {
    label: "Total Customers",
    value: "50000",
    change: "+8.2%",
    trend: "up",
    tone: "blue",
    iconSrc: "/images/dashboard/customers/total.svg",
  },
  {
    label: "VIP Customers",
    value: "284",
    change: "+8.2%",
    trend: "up",
    tone: "green",
    iconSrc: "/images/dashboard/customers/vip.svg",
  },
  {
    label: "Active Customers",
    value: "1,284",
    change: "-5.1%",
    trend: "down",
    tone: "orange",
    iconSrc: "/images/dashboard/customers/active.svg",
  },
  {
    label: "Inactive Customers",
    value: "200",
    change: "-5.1%",
    trend: "down",
    tone: "gray",
    iconSrc: "/images/dashboard/customers/inactive.svg",
  },
];

export const mockCustomers: CustomerRow[] = [
  {
    id: "BK-TR01-1",
    name: "Ahmed Hassan",
    email: "josh_adam@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Egyptian",
    bookings: 1,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Inactive",
  },
  {
    id: "BK-TR01-2",
    name: "Linda Blair",
    email: "lindablair@mail.com",
    phone: "+20 101 234 5678",
    nationality: "American",
    bookings: 2,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Inactive",
  },
  {
    id: "BK-TR01-3",
    name: "Mohammad Karim",
    email: "m_karim@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Spanish",
    bookings: 4,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Inactive",
  },
  {
    id: "BK-TR01-4",
    name: "Ilham Budi Agung",
    email: "ilahmbudi@mail.com",
    phone: "+20 101 234 5678",
    nationality: "American",
    bookings: 1,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Active",
  },
  {
    id: "BK-TR01-5",
    name: "John Bushmill",
    email: "Johnb@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Spanish",
    bookings: 5,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Inactive",
  },
  {
    id: "BK-TR01-6",
    name: "Linda Blair",
    email: "ilahmbudi@mail.com",
    phone: "+20 101 234 5678",
    nationality: "American",
    bookings: 2,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Active",
  },
  {
    id: "BK-TR01-7",
    name: "Josh Adam",
    email: "Johnb@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Japanese",
    bookings: 2,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Inactive",
  },
  {
    id: "BK-TR01-8",
    name: "Linda Blair",
    email: "ilahmbudi@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Japanese",
    bookings: 2,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Active",
  },
  {
    id: "BK-TR01-9",
    name: "Linda Blair",
    email: "ilahmbudi@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Japanese",
    bookings: 2,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Blocked",
  },
  {
    id: "BK-TR01-10",
    name: "Linda Blair",
    email: "ilahmbudi@mail.com",
    phone: "+20 101 234 5678",
    nationality: "Japanese",
    bookings: 2,
    totalSpent: "£8,250",
    lastActivity: "Mar 15, 2024",
    status: "Active",
  },
];
